number = int(input('Digite Um Número Para Saber A Tabuada Dele: '))

print('-------------')
print('{} X {} = {}'.format(number, 1, number*1))
print('{} X {} = {}'.format(number, 2, number*2))
print('{} X {} = {}'.format(number, 3, number*3))
print('{} X {} = {}'.format(number, 4, number*4))
print('{} X {} = {}'.format(number, 5 , number*5))
print('{} X {} = {}'.format(number, 6, number*6))
print('{} X {} = {}'.format(number, 7, number*7))
print('{} X {} = {}'.format(number, 8, number*8))
print('{} X {} = {}'.format(number, 9, number*9))
print('{} X {} = {}'.format(number, 10, number*10))
print('-------------')